apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wp-cronjob
spec:
  schedule: "0 0 1,15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wordpress
            image: wordpress
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
            args:
            - /bin/sh
            - -c
            - date; echo Hello GKE!
          restartPolicy: OnFailure

